package com.example.accessingdatamysql;

import java.util.List;
import java.util.Map;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private MascotasRepository MascotasRepository;

  @Autowired
  private JdbcTemplate jdbcTemplate;


  @PostMapping(path="/add") // Map ONLY POST Requests
  public @ResponseBody String addNewmascotas (@RequestParam String name
      , @RequestParam String raza
      , @RequestParam String propietario  ) {
    // @ResponseBody means the returned String is the response, not a view name
    // @RequestParam means it is a parameter from the GET or POST request

    mascotas n = new mascotas();
    n.setName(name);
    n.setRaza(raza);
    n.setPropietario(propietario);
    MascotasRepository.save(n);
    return "Saved";
  }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<mascotas> getAllmascotas() {
    // This returns a JSON or XML with the users
    return MascotasRepository.findAll();
  }

  @PutMapping(path="/edit")
  public @ResponseBody String editmascotas(@RequestParam String name, @RequestParam String raza, @RequestParam String propietario, @RequestParam Integer id) {
    mascotas n = new mascotas();
    n.setId(id);
    n.setName(name);
    n.setraza(raza);
    n.setPropietario(propietario);
    MascotasRepository.save(n);
    return "Edited";
  }
    
  @GetMapping(path="/ver/{id}")
  public @ResponseBody mascotas getMascotas(@PathVariable Integer id) {
    return MascotasRepository.findById(id).get();
  }

  @DeleteMapping(path="/del")
  public @ResponseBody String editmascotas(@RequestParam Integer id) {
    mascotas n = new mascotas();
    n.setId(id);
    MascotasRepository.delete(n);
    return "Delete";
  }

  @GetMapping(path="/get/report")
  public @ResponseBody List<Map<String, Object>> getReport(){
    String sql = "SELECT CONCAT(name, '(nombre) ==> (raza)', raza ==> (propietario)', propietario) as MIS_Mascotas FROM mascotas;";
    List<Map<String, Object>> mascotas = jdbcTemplate.queryForList(sql);
    return mascotas;

  }

}